pitstop/routes/auth.py
# Import necessary modules from Flask and other packages
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, current_user
from pitstop.models.models import User
from pitstop.extensions import bcrypt, db
from pitstop.utils import format_phone_number, send_custom_email
import uuid

# Create a Blueprint for authentication-related routes
auth = Blueprint('auth', __name__)

@auth.route('/register', methods=['GET', 'POST'])
def register():
    """
    Handles the user registration process. 
    - GET request: displays the registration form.
    - POST request: processes the form data to register a new user.
    """

    if current_user.is_authenticated:
        flash(f'You are already logged in as {current_user.username}')
        return redirect(url_for('dashboard.dashboard_route'))
    
    if request.method == 'POST':
        # Retrieves data from the request
        first_name = request.form.get('first_name')
        last_name = request.form.get('last_name')
        username = request.form.get('username')
        email = request.form.get('email')
        password = request.form.get('password')
        phone = request.form.get('phone_number')

        # Hash user password
        user_password = bcrypt.generate_password_hash(password).decode('utf-8')

        # Creating a new user object
        new_user = User(
            id=uuid.uuid4().hex,
            first_name=first_name,
            last_name=last_name,
            username=username,
            email=email,
            phone=format_phone_number(phone),
            password=user_password
        )

        # Add the new user to the database and commit the changes
        db.session.add(new_user)
        db.session.commit()

        # Notify the user and redirect to the login page
        flash('You can now login to access your account')
        return redirect(url_for('auth.login'))

    # Render the registration form template
    return render_template('register.html', title='Portfolio project')

@auth.route('/login', methods=['GET', 'POST'])
def login():
    """
    Handles the user login process.
    - GET request: processes login data and attempts authentication.
    - POST request: handles the actual login process.
    """

    if current_user.is_authenticated:
        flash(f'Already loggen in as {current_user.username}')
        return redirect(url_for('dashboard.dashboard_route'))
    

    if request.method == 'GET':
        # Redirects already logged-in users to the dashboard
        email = request.args.get('email')
        password = request.args.get('password')
        remember = request.args.get('remember')

        # Find the user by email
        user = User.query.filter_by(email=email).first()


        if user is None and email is not None:
            # checks if there is nouser in the database but they have entered the email on their end
            flash('No Account found for that Email! Consider Registering')
            return redirect(url_for('auth.login'))
        

        if user:
            if bcrypt.check_password_hash(user.password, password):
                # Log the user in and redirect to the dashboard
                login_user(user, remember=remember)
                flash(f'Logged in as {current_user.username}!')
                return redirect(url_for('dashboard.dashboard_route'))
            else:
                flash('incorect password')
                return redirect(url_for('auth.login'))
        
    # Rendering the login page Template
    return render_template('login.html', title="Portfolio project")

@auth.route('/logout')
def logout():
    """
    Logs out the current user and redirects to the home page.
    """
    logout_user()
    return redirect(url_for('home.home_testing'))



@auth.route('/login/forgot_password', methods=['GET', 'POST'])
def reset_request():
    """
    Handles password reset requests.
    - GET request: displays the password reset request form.
    - POST request: processes the form data and sends a password reset email if the email is associated with a user.
    """

    if request.method == 'POST':
        email = request.form.get('email')
        user = User.query.filter_by(email=email).first()
        if user is not None:
            token  = user.get_reset_token()
            message = f'''Hello {user.first_name},
To reset your password, follow the folowing link:
{url_for('auth.reset_password', token=token, _external=True)}

If you did not make this request, simply ignore this email and no changes will be made.
'''
            send_custom_email(
                subject='Password Reset Request',
                recipient=[user.email],
                message=message
            )
            flash('An Email has been sent with instructions to reset your password.')
            return redirect(url_for('auth.login'))
        else:
            flash('Email not found in our database', 'danger')
    return render_template('reset_request.html', title='Forgot password | PITSTOP')


@auth.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    """
    Handles the password reset process.
    - GET request: verifies the reset token and displays the password reset form.
    - POST request: processes the new password and updates it if valid.
    """

    user = User.verify_reset_token(token)

    if request.method == 'POST':
        password = request.form.get('password')
        confirm_password = request.form.get('confirm_password')

        if password != confirm_password:
            flash('Paswords must match')

        else:
            # Update the user's password and commit the changes
            user_password = bcrypt.generate_password_hash(password).decode('utf-8')
            user.password = user_password
            db.session.commit()
            flash('Your password has been updated, You are now able to log in')
            return redirect(url_for('auth.login'))

    if request.method == 'GET':
        if not user:
            flash('That is an Invalid or Expired token')
            return redirect(url_for('auth.reset_request'))
        
    # REndering the page template
    return render_template('reset_password.html', title='Reset password')

pitstop/routes/dashboard.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import current_user

dashboard = Blueprint('dashboard', __name__)

@dashboard.route('/dashboard')
def dashboard_route():
    """
    Handles the display of the dashboard page.
    - Checks if the user is authenticated.
    - If the user is not authenticated, redirects to the home page with a flash message.
    - If the user is authenticated, renders the dashboard page.
    """
    
    if not current_user.is_authenticated:
        flash('You must first log in to access the platform')
        return redirect(url_for('home.home_testing'))
    return render_template('dashboard.html', title="Portfolio project", user=current_user)

pitstop/routes/services.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user
from pitstop.models.models import Service, Booking, Vehicle, TechnicianBooking, Technician
from pitstop.extensions import db
from pitstop.utils import send_custom_email, send_sms
from datetime import datetime
from pitstop.config import Config
import uuid

services = Blueprint('services', __name__)

@services.route('/services')
def service_list():
    """
    Displays a list of services booked by the current user.
    - Fetches bookings for the current user.
    - Joins related Service, TechnicianBooking, and Technician data.
    - Paginates the results to show 5 bookings per page.
    - Renders the 'services.html' template with the bookings.
    """

    if not current_user.is_authenticated:
        flash('You must first log in to access that page')
        return redirect(url_for('home.home_testing'))
    
    date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    page = request.args.get('page', 1, type=int)

    bookings = db.session.query(
        Booking.id,
        Booking.appointment_time,
        Booking.status,
        Service.name.label('service_name'),
        Technician.name.label('technician_name'),
        TechnicianBooking.comment.label('technician_comment')
    ).join(Service, Booking.service_id == Service.id)\
        .join(TechnicianBooking, TechnicianBooking.booking_id == Booking.id)\
            .join(Technician, Technician.id == TechnicianBooking.technician_id)\
                .filter(Booking.user_id == current_user.id)\
                    .order_by(Booking.id.desc())\
                        .paginate(page=page, per_page=5)


    return render_template('services.html', time=date, title='Portfolio project', bookings=bookings)

@services.route('/services/new', methods=['GET', 'POST'])
def service_request():
    """
    Handles the service request form.
    - On GET: Displays the form to request a new service.
    - On POST: Processes the form submission, creates a new booking, and assigns a technician.
    - Sends an email and SMS notification to the admin.
    """

    if not current_user.is_authenticated:
        flash('You must first log in to access that page')
        return redirect(url_for('home.home_testing'))
    
    if request.method == 'POST':
        vehicle_name = request.form.get('vehicle_id')
        service = request.form.get('service_id')
        description = request.form.get('description')
        appointment_time = request.form.get('appointment_time')

        # Check if service exists in the database
        service_type = Service.query.filter_by(name=service).first()
        if not service_type:
            service_type = Service(
                id=uuid.uuid4().hex,
                name=service,
                price=300.00
            )
            db.session.add(service_type)
            db.session.commit()



        # Check if the vehicle exists in the database
        vehicle_id = Vehicle.query.filter_by(make=vehicle_name).first()
        if not vehicle_id:
            flash('Selected vehicle does not exist.')
            return redirect(url_for('services.service_request'))
        
        # Create a new booking with the provided data
        new_booking = Booking(
            id=uuid.uuid4().hex,
            user_id=current_user.id,
            service_id=service_type.id,
            appointment_time=datetime.fromisoformat(appointment_time),
            status='Pending',
            description=description,
            vehicle_id=vehicle_id.id
        )
        # Add the new booking to the database session and commit it
        db.session.add(new_booking)
        
        '''
            THE BELOW CODE IS JUST FOR TESTING AND THE REAL IMPLEMENTATION OF FINDING
            THE REAL TECHNICIAN WILL BE IMPLEMENTED IN THE NEAR FUTURE - STAY TUNED
        '''
        tech = Technician.query.first()
        
        assign_tech = TechnicianBooking(
            id=uuid.uuid4().hex,
            technician_id=tech.id,
            booking_id=new_booking.id,
            comment='working on it!'
        )
        # Add the new tech to the database session and commit it
        db.session.add(assign_tech)
        '''
            THE ABOVE CODE IS JUST FOR TESTING AND THE REAL IMPLEMENTATION OF FINDING
            THE REAL TECHNICIAN WILL BE IMPLEMENTED IN THE NEAR FUTURE - STAY TUNED
        '''
        db.session.commit()
        message = f'''Greetings Admin,
A user {current_user.first_name} {current_user.last_name} has requested a service
for his vehicle {vehicle_id.make} {vehicle_id.model} and expects his service to be done by the date: {appointment_time}.

service: {service}
service description: {description}

contact information:
    Email: {current_user.email}
    Phone number: {current_user.phone}

Check your dashboard for more information about this.
Have a nice day!


'''
        try:
            send_custom_email(
            subject='New Scheduled service',
            recipient=[Config.MAIL_USERNAME], # 🔐|📒 This is to be changed later when we have admins to our platform
            message=message
            )
            flash(f'{service} service scheduled')
        except Exception as e:
            flash('An error occured. Please try again!')
            return redirect(url_for('services.service_request'))
        
        # This function handles the errors, that's why it is not sorrounded with a try/except block
        send_sms(message)
       
        return redirect(url_for('dashboard.dashboard_route'))

    # Query the user's vehicles and all available services
    user_vehicles = Vehicle.query.filter_by(user_id=current_user.id).all()
    services = Service.query.all()

    # Try to pass service from dashboard
    spec_service = request.args.get('service')
    print(f'Spec value: {spec_service}')

    #requesting a vehicle maintenance from vehicles route
    spec_vehicle = request.args.get('vehicle') 

    # Render the service request template with user vehicles and services
    return render_template('service_request.html',
                           title='Request a New Service',
                           user=current_user,
                           vehicles=user_vehicles,
                           services=services,
                           spec_service=spec_service,
                           spec_vehicle=spec_vehicle)

pitstop/routes/test_user.py
from flask import Blueprint, render_template, abort
from pitstop.models.models import User, Vehicle, Service, Booking, Technician, TechnicianBooking, Admin
from pitstop.config import Config
#============= TEST API ==============#


test = Blueprint('test', __name__)



# This route is only for the admin with admin key now.
@test.route('/database/<key>', methods=['GET'])
def display_database(key):

    if not key or key != Config.ADMIN_KEY:
        abort(404)
    
    # Fetch all entries from different tables
    users = User.query.all()
    vehicles = Vehicle.query.all()
    services = Service.query.all()
    bookings = Booking.query.all()
    technicians = Technician.query.all()
    technician_bookings = TechnicianBooking.query.all()
    return render_template('database.html', 
                           users=users, 
                           vehicles=vehicles, 
                           services=services, 
                           bookings=bookings, 
                           technicians=technicians,
                           technician_bookings=technician_bookings)

@test.route('/about')
def about():
    """
    Renders the 'about' page.
    - Displays the 'about.html' template with the title 'About'.
    """
    return render_template('about.html', title='About')

pitstop/routes/vehicles.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import current_user
from pitstop.models.models import Vehicle, Booking
from pitstop.extensions import db
from pitstop.config import Config
import uuid

vehicles = Blueprint('vehicles', __name__)

@vehicles.route('/vehicles')
def vehicle_list():
    """
    Renders the list of vehicles for the current user.
    - Queries vehicles belonging to the current user.
    - Renders the 'vehicles.html' template with the list of vehicles.
    """

    vehicles = Vehicle.query.filter_by(user_id=current_user.id)
    return render_template('vehicles.html', title='Portfolio Project', vehicles=vehicles)

@vehicles.route('/vehicles/new', methods=['GET', 'POST'])
def new_vehicle():
    """
    Handles the addition of a new vehicle.
    - On GET: Renders the 'new_vehicle.html' template for adding a new vehicle.
    - On POST: Processes the form data to add a new vehicle.
    """

    if request.method == 'POST':
        plate = request.form.get('license_plate')

        exists = Vehicle.query.filter_by(license_plate=plate).first()

        if exists:
            flash('That car is already managed by another user!')
        else:
            vehicle = Vehicle(
                id=uuid.uuid4().hex,
                user_id=current_user.id,
                make=request.form.get('vehicle_brand'),
                model=request.form.get('vehicle_model'),
                year=request.form.get('year'),
                type=request.form.get('type'),
                color=request.form.get('color'),
                license_plate=request.form.get('license_plate')
            )
            db.session.add(vehicle)
            db.session.commit()
            print('done')
            flash(f'{request.form.get("vehicle_brand")} {request.form.get("vehicle_model")} successfully added!')
            return redirect(url_for('vehicles.vehicle_list'))
    return render_template('new_vehicle.html', title="Portfolio project")


@vehicles.route('/vehicle/<string:vehicle_id>', methods=['GET'])
def delete_vehicle(vehicle_id):
    """
    Handles the deletion of a vehicle.
    - Finds the vehicle by ID.
    - Updates bookings associated with the vehicle to indicate deletion.
    - Deletes the vehicle from the database.
    """

    vehicle = Vehicle.query.get_or_404(vehicle_id)
    booking = Booking.query.filter_by(vehicle_id=vehicle.id).all()
    for order in booking:
        order.vehicle_id = f'Was owned by {current_user.first_name} {current_user.last_name}'
        order.status = 'vehicle deleted'
        order.technician_bookings.comment = 'repair cancelled'
    db.session.delete(vehicle)
    db.session.commit()
    return redirect(url_for('vehicles.vehicle_list'))

pitstop/templates/dashboard.html
{% extends 'layout.html' %}
{% block content %}
<div class="dashboard-container">
    <section class="quick-actions">
        <div class="actions">
            <a class="link-regular" href="{{ url_for('vehicles.new_vehicle') }}">Add Vehicles</a>
            <a href="{{ url_for('services.service_request') }}" class="link-regular">Schedule Service</a>
            <a href="#" class="link-regular">Support center</a>
        </div>
    </section>
    <div class="dashboard-section">
        <section class="activity-feed">
            <h3>Recent Activity</h3>
            <ul>
                <li>Task "Fix Brakes" completed</li>
                <li>Service "Oil Change" scheduled</li>
                <li>New vehicle added</li>
            </ul>
        </section>
        <section class="upcoming-appointments">
            <h3>Upcoming Appointments</h3>
            <ul>
                <li>Oil Change - July 10, 2024</li>
                <li>Tire Replacement - July 15, 2024</li>
            </ul>
        </section>
        <section class="notifications">
            <h3>Notifications</h3>
            <ul>
                <li>Reminder: Service appointment tomorrow</li>
                <li>Update: Task "Check Engine" due soon</li>
            </ul>
        </section>
    </div>
    <div class="services-dash">
        <h2 class="section-title">Recommended Services</h2>
        <div class="service-dash-list">
            <div class="service-dash-item">
                <h3>Oil Change</h3>
                <p>Keep your engine running smoothly with regular oil changes. Recommended every 3,000 to 5,000 miles.</p>
                <a class="link-regular" href="{{ url_for('services.service_request', service='Oil Change') }}">Schedule</a>
            </div>
            <div class="service-dash-item">
                <h3>Brake Inspection</h3>
                <p>Ensure your safety with regular brake inspections. We check pads, rotors, and fluid levels.</p>
                <a class="link-regular" href="{{ url_for('services.service_request', service='Brake Inspection') }}">Schedule</a>
            </div>
            <div class="service-dash-item">
                <h3>Battery Check</h3>
                <p>Don't get stranded with a dead battery. Regular checks can help avoid unexpected issues.</p>
                <a class="link-regular" href="{{ url_for('services.service_request', service='Battery Replacement') }}">Schedule</a>
            </div>
            <div class="service-dash-item">
                <h3>Tire Rotation</h3>
                <p>Extend the life of your tires and improve your vehicle's performance with regular rotations.</p>
                <a class="link-regular" href="{{ url_for('services.service_request', service='Tire Rotation') }}">Schedule</a>
            </div>
        </div>
    </div>
    <!-- <section class="user-stats">
        <h3>User Stats</h3>
        <div class="stats-chart">
        </div>
    </section> -->
</div>
{% endblock content %}

pitstop/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/home.css') }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@100;300;400;500;600;700&family=Montserrat:wght@700;800;900&display=swap">
    <title>{{ title }}</title>
</head>

<body>
    <div class="content">
        <nav class="hero">
            <h3 class="logo">PIT<span class="logo-design">STOP</span></h3>
            <ul>
                <li><a href="#">Home</a></li>
                <li><a href="#about" class="smooth">About</a></li>
            </ul>
            <a href="{{ url_for('auth.login') }}"><button class="nav-cto">Log in</button></a>
        </nav>
        <div class="flash-container">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="flash-message">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
        <h1 class="heading-1">MECHANICS ON THE MOVE</h1>
        <h1 class="heading-2">FOR CARS THAT CAN'T</h1>
        <p class="center-text">At PITSTOP, we turn car troubles into smooth rides. Our expert mechanics come to <span class="blue-bold">YOU</span>, delivering top-tier service wherever your car rests. Say goodbye to downtime and hello to effortless auto care!</p>
        <a href="{{ url_for('auth.register') }}"><button class="cto-content">GET STARTED</button></a>




        <!-- Features Section -->
        <section id="features" class="features-section">
            <div class="features-container">
                <h3>Key Features</h3>
                <div class="feature">
                    <img src="{{ url_for('static', filename='images/feature_1.jpg') }}" alt="Feature 1">
                    <p>Effortlessly schedule maintenance and repairs with our user-friendly interface.</p>
                </div>
                <div class="feature">
                    <img src="{{ url_for('static', filename='images/feature_1.jpg') }}" alt="Feature 1">
                    <p>Track your vehicle’s service history and get reminders for upcoming services.</p>
                </div>
                <div class="feature">
                    <img src="{{ url_for('static', filename='images/feature_1.jpg') }}" alt="Feature 1">
                    <p>Get real-time updates on your service status from our expert mechanics.</p>
                </div>
            </div>
        </section>



        <!-- About Section -->
        <section id="about" class="about-section">
            <div class="about-container">
                <h2>About PitStop</h2>
                <div class="about-content">
                    <div class="story">
                        <h3>My Journey</h3>
                        <p>PitStop was born from the realization that many car owners face recurring issues with vehicle maintenance but struggle to keep track of services and schedules. Seeing a gap in the market for a comprehensive, user-friendly platform, I was inspired to create PitStop. This platform is designed to efficiently manage all vehicle-related services, offering a holistic approach to tracking maintenance histories, scheduling appointments, and providing essential car care tips. As the sole creator, I am dedicated to making car maintenance hassle-free and invite you to join me on this journey towards smarter, simpler car care.</p>
                        <p>This project is also my Portfolio Project for <a href="https://holbertonschool.com" target="_blank">Holberton School</a>, showcasing my skills in web development and design.</p>
                    </div>
                    <div class="links">
                        <h3>Connect with Me</h3>
                        <ul>
                            <li><a href="https://www.linkedin.com/in/pr1est/" target="_blank">LinkedIn</a></li>
                            <li><a href="https://github.com/PRIEST099" target="_blank">GitHub</a></li>
                            <li><a href="https://twitter.com/a_had_i_" target="_blank">Twitter</a></li>
                        </ul>
                    </div>
                    <div class="repository">
                        <h3>Project Repository</h3>
                        <p>Check out the code and contribute to the project on <a href="https://github.com/PRIEST099/pitstop" target="_blank">GitHub</a>.</p>
                    </div>
                </div>
            </div>
        </section>

       
    </div>
</body>

</html>

pitstop/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/layout.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/dashboard.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/vehicles.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles/services.css') }}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Josefin+Sas:ital, wght@0,100;0,300;0,400;0,500;0,600;0,700;1,100;1,200;1,300;1,400;1,500;1,600;1,700&family=Montserrat:wght@700;800;900&display=swap">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{{ url_for('static', filename='scripts/flash.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/load_tips.js') }}"></script>
    <script src="{{ url_for('static', filename='scripts/date.js') }}"></script>
    <title>{{title}}</title>
</head>
<body>
    <div class="content">
        <nav class="hero">
            <h3 class="logo">PIT<span class="logo-design">STOP</span></h3>
            <ul>
                <li><a href="{{ url_for('dashboard.dashboard_route') }}">Dashboard</a></li>
                <li><a href="{{ url_for('vehicles.vehicle_list') }}">My vehicles</a></li>
                <li><a href="{{ url_for('services.service_list') }}">My services</a></li>
                <li><a href="{{ url_for('test.about') }}">About</a></li>
                <li><a href="#">Support</a></li>
            </ul>
            <a href="{{ url_for('auth.logout') }}"><button class="nav-cto">Log out</button></a>
                
        </nav>
        <div class="flash-container">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="flash-message">{{ message }}</div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
        <h4 class="title-tip">-</h4>
        <p class="center-text tip">--</p>
    </div>
    <div class="layout-content">
        {% block content %}{% endblock content %}
    </div>
    <footer class="site-footer blur">
        <div class="footer-content">
            <div class="footer-section about">
                <h2>PIT<span class="logo-design">STOP</span></h2>
                <p>Your one-stop solution for all vehicle maintenance needs. Stay on top of your vehicle's health with PITSTOP.</p>
                <div class="contact">
                    <span><i class="fas fa-phone"></i> &nbsp; +250 789 108 997</span>
                    <span><i class="fas fa-envelope"></i> &nbsp; support@pitstop.com</span>
                </div>
                <div class="socials">
                    <a href="#"><i class="fab fa-facebook"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                </div>
            </div>

            <div class="footer-section links">
                <h2>Quick Links</h2>
                <br>
                <ul>
                    <li><a href="#">Events</a></li>
                    <li><a href="#">Team</a></li>
                    <li><a href="#">Mentors</a></li>
                    <li><a href="#">Gallery</a></li>
                    <li><a href="#">Terms and Conditions</a></li>
                </ul>
            </div>

            <div class="footer-section contact-form">
                <h2>Contact us</h2>
                <br>
                <form action="{{ url_for('support.support_response')}}" method="post">
                    <input type="text" name="subject" class="text-input contact-input" placeholder="Email subject" required>
                    <textarea name="message" class="text-input contact-input" placeholder="Your message..." required></textarea>
                    <button type="submit" class="form-submit">Send</button>
                </form>
            </div>
        </div>

        <div class="footer-bottom">
            &copy; Holberton School Portfolio Project
        </div>
    </footer>
</body>
</html>

pitstop/templates/services.html
{% extends 'layout.html' %}

{% block content %}
<div class="services">
    <h2 class="section-title">My Services</h2>
    <div class="service-timeline">
        <div class="timeline-item">
            <div class="timeline-date">
                <p>Today</p>
            </div>
            <a href="{{ url_for('services.service_request') }}" class="timeline-content-button">Schedule a new service</a>
        </div>
        {% for order in bookings.items %}
        <div class="timeline-item">
            <div class="timeline-date {% if order.status != 'complete' %}pending{% else %}completed{% endif %}">
                <p>{{order.appointment_time}}</p>
            </div>
            <div class="timeline-content">
                <h3>{{ order.service_name }} - <small class="{% if order.status != 'complete' %}pending{% else %}completed{% endif %}">{{ order.status }}</small></h3>
                <p>Served by <a class="red">{{order.technician_name}}</a>. {{ order.technician_comment }}</p>
            </div>
        </div>
        {% endfor %}
        <div class="pagination-link">
            {% for page_num in bookings.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=1) %}
                {% if page_num %}
                    {% if bookings.page == page_num %}
                        <a class="current-page"  href="{{ url_for('services.service_list', page=page_num) }}">{{ page_num }}</a>
                    {% else %}
                        <a  href="{{ url_for('services.service_list', page=page_num) }}">{{ page_num }}</a>
                    {% endif %}
                    
                {% else %}
                    ...
                {% endif %}
            {% endfor %}
        </div>
        
    </div>
</div>
{% endblock %}